### ISSUE TITLE
Main Roadmap

### ISSUE THREAD

**Issue by ajmnz** [ajmnz/translate.dogehouse.tv#1]
**Top**

- [ ] Fetch latest strings from dogehouse

---

- [ ] Finish auth and display top bar with avatar + username
- [ ] Official language reviewers
    - [ ] Create feed of revisable strings
    - [ ] Approve or edit/request changes
        - [ ] If approved goes to prod, if edited too (?)
        - [ ] i18n return only approved strings
- [ ] Post routes for adding untranslated strings (auth exclusive)
- [ ] Revise should be only for official reviewers

**Comment by BronzW** [comment]
Is there more components of mansaf that needs to be done? And if so, is there a design?

**Comment by BronzW** [comment]
Happy to contribute

**Comment by ajmnz** [comment]
Hey, I'm still setting up some stuff before I can take any contributions. And there's no design, I've been figuring out stuff as I coded it

**Comment by BronzW** [comment]
Cool
